name: TransWarp
version: ${project.version}
main: me.ansandr.transwarp.TransWarp
api-version: 1.13
depend: [ Essentials ]
softdepend: [ Vault, EssentialsSpawn, GPS ]
authors: [ Ansandr ]
description: Introduces a transport system for realystic and quickly adventure around the world

commands:
  settransport:
    usage: /<command> <transName> <transportType>
    aliases:
      - settrans
    description: Установить транспорт на вашем месте
  transport:
    description: Приехать на транспорте
  transwarp:
    usage: /<command> <args...>
    description: Главная комманда
permissions:
  transwarp.bypass:
    description: Позволяет игроку игнорировать транспорт
    default: false
  transwarp.fast:
    description: Поволяет игроку выбирать моментальную телепортироватацию на точку
    default: op
  transwarp.skip:
    description: Доступ к комманде /transwarp skip
    default: op
  transwarp.bypass.economy:
    description: Позволяет игнорировать цены в транспортах
    default: false
  transwarp.bypass.world:
    description: Позволяет игнорировать различие в мирах
    default: false