name: TransWarp
version: ${project.version}
main: me.ansandr.transwarp.TransWarp
api-version: 1.13
depend: [ Essentials]
softdepend: [ Vault, EssentialsSpawn ]
authors: [ Ansandr ]
description: Introduces a transport system for realystic and quickly adventure around the world

commands:
  settransport:
    usage: /<command> <transName> <transportType>
    aliases:
      - settrans
    description: Установить транспорт на вашем месте
  transport:
    description: Приехать на транспорте
  transwarp:
    description: Главная комманда
permissions:
  transwarp.bypass:
    description: Позволяет игроку игнорировать транспорт
    default: false
  transwarp.fast:
    description: Поволяет игроку выбирать моментальную телепортироватацию на точку